---

- name: Apt update cache (apt)
  ansible.builtin.apt:
    update_cache: true

- name: Install openjdk-8-jre-headless
  ansible.builtin.apt:
    name: openjdk-8-jre-headless
    state: present

- name: Install logstash
  ansible.builtin.apt:
    name: logstash
    state: present

#- name: Copy logstash configuration 1
#  ansible.builtin.copy:
#    src: ./apache_access_log_logstash.lconf
#    dest: /etc/logstash/conf.d/apache_access_log_logstash.conf
#    force: true
#    owner: root
#    group: elasticsearch
#    mode: u=rw,g=rw,o=r
#
#- name: Copy logstash configuration 2
#  ansible.builtin.copy:
#    src: ./json_log_logstash.lconf
#    dest: /etc/logstash/conf.d/json_log_logstash.conf
#    force: true
#    owner: root
#    group: elasticsearch
#    mode: u=rw,g=rw,o=r
#
#- name: Copy logstash configuration 3
#  ansible.builtin.copy:
#    src: ./json_drop_logstash.lconf
#    dest: /etc/logstash/conf.d/json_drop_logstash.conf
#    force: true
#    owner: root
#    group: elasticsearch
#    mode: u=rw,g=rw,o=r
#
#- name: Copy logstash configuration 4
#  ansible.builtin.copy:
#    src: ./json_split_logstash.lconf
#    dest: /etc/logstash/conf.d/json_split_logstash.conf
#    force: true
#    owner: root
#    group: elasticsearch
#    mode: u=rw,g=rw,o=r
#
#- name: Copy logstash configuration 5
#  ansible.builtin.copy:
#    src: ./json_split_structured_logstash.lconf
#    dest: /etc/logstash/conf.d/json_split_structured_logstash.conf
#    force: true
#    owner: root
#    group: elasticsearch
#    mode: u=rw,g=rw,o=r
# Run logstash:
# cd  cd /usr/share/logstash
# sudo bin/logstash -f /etc/logstash/conf.d/apache_access_log_logstash.lconf

